name: EZContent Article Feature
description: 'Provides article content type.'
recipes:

install:
  - ezcontent_theme
  - ezcontent_node
  - ezcontent_paragraphs
  - autocomplete_deluxe:autocomplete_deluxe
  - diff:diff
  - entityqueue:entityqueue
  - length_indicator:length_indicator
  - schema_metatag:schema_article
  - yoast_seo

config:
  import:
    ezcontent_paragraphs: '*'

  actions:
      system.theme:
        simple_config_update:
          default: ezcontent_theme
      user.role.content_editor:
        ensure_exists:
          id: content_editor
        grantPermissions:
          - 'create article content'
          - 'delete any article content'
          - 'delete article revisions'
          - 'delete own article content'
          - 'edit any article content'
          - 'edit own article content'
          - 'revert article revisions'
          - 'view article revisions'
          - 'break content lock'
          - 'use yoast seo'

    # When a theme is enabled in Drupal, the blocks of the existing theme are
    # automaticaly duplicated. In our case, on standard, the theme is claro.
    # We set the blocks we don't want to false, and alter the config of the
    # blocks that were created.
      block.block.ezcontent_theme_account_menu:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_breadcrumbs:
        simple_config_update:
          status: false
      block.block.ezcontent_theme_content:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_help:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_main_menu:
        simple_config_update:
          region: primary_menu
          weight: 0

      block.block.ezcontent_theme_messages:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_page_title:
        simple_config_update:
          langcode: en
          status: true
          dependencies:
            module:
              - node
            theme:
              - ezcontent_theme
          id: ezcontent_theme_page_title
          theme: ezcontent_theme
          region: content
          weight: 0
          provider: null
          plugin: page_title_block
          settings:
            id: page_title_block
            label: 'Page title'
            label_display: '0'
            provider: core
          visibility:
            'entity_bundle:node':
              id: 'entity_bundle:node'
              negate: false
              context_mapping:
                node: '@node.node_route_context:node'
              bundles:
                article: article
                page: page

      block.block.ezcontent_theme_powered:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_primary_admin_actions:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_primary_local_tasks:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_search_form_narrow:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_search_form_wide:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_secondary_local_tasks:
        simple_config_update:
          status: false

      block.block.ezcontent_theme_syndicate:
        simple_config_update:
          status: false
